archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make build_provider
blobs:
  - bucket: get.pulumi.com
    folder: releases/plugins/
    ids:
      - archive
    provider: s3
    region: us-west-2
builds:
  - binary: pulumi-resource-aws-quickstart-aurora-postgres
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/pulumi/pulumi-aws-quickstart-aurora-postgres/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-aws-quickstart-aurora-postgres/
changelog:
  skip: true
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
